opun.sks.Presentation.Website/Models/RegionsPackagesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EntityRepo.Entities;

namespace opun.sks.Presentation.Website.Models
{
	public class RegionsPackagesViewModel
	{
		public List<Package> Packages { get; set; }
		public List<Region> Regions { get; set; }

		public RegionsPackagesViewModel()
		{
			Packages = new List<Package>();
			Regions = new List<Region>();
		}
	}
}

opun.sks.Presentation.Website/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace opun.sks.Presentation.Website.Controllers
{
	public class HomeController : Controller
	{

		public ActionResult Index()
		{
            log4net.Config.XmlConfigurator.Configure();
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "BIF-5 Software Komponenten Systeme";

			return View();
		}

		public ActionResult Contact()
		{
			return View();
		}
	}
}

opun.sks.Presentation.Website/Controllers/PackageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using DAL.OutMemory;
using DALInterfaces.Interfaces.Agents;
using DALInterfaces.Interfaces.Presentation;
using DALInterfaces.Interfaces.Repositories;
using DALInterfaces.Interfaces.Services;
using EntityRepo.Entities;
using GeodataService;
using Microsoft.Practices.Unity;
using Microsoft.Practices.Unity.Configuration;
using Opitz_Unterbrunner_SKS;
using Opitz_Unterbrunner_SKS.PresentationLogic;
using opun.sks.Presentation.Website.Models;

namespace opun.sks.Presentation.Website.Controllers
{
	public class PackageController : Controller
	{
		private IRegionLogic regionLogic;
		private IPackageLogic packageLogic;
		private List<Package> packages;
		public List<SelectListItem> itemList { get; set; }
		IUnityContainer container { get; set; }

		public PackageController()
		{
			container = new UnityContainer();
			
			container.LoadConfiguration();

			regionLogic = container.Resolve<IRegionLogic>();
			packageLogic = container.Resolve<IPackageLogic>();

			List<Region> regions = new List<Region>(regionLogic.GetAll());
			var items = regions.Select(r => new SelectListItem
					{
						Value = r.Key,
						Text = r.Key
					});
			itemList = new List<SelectListItem>(items);
		}

		//
		// GET: /Package/
		public ActionResult Index()
		{
			packages = new List<Package>(packageLogic.GetAll());
			packages = packages.Where(p => p.Delivered == false).ToList();
			ViewBag.RegionKeys = itemList;

			return View(packages);
		}

		[HttpPost]
		public ActionResult Index(string selectRegion)
		{
			ViewBag.SelectedKey = selectRegion;
			packages = new List<Package>(packageLogic.GetDeliveredByRegionKey(selectRegion, false));
			ViewBag.RegionKeys = itemList;

			return View(packages);
		}

		[HttpPost]
		public ActionResult Delivered(FormCollection collection)
		{
			string key = collection["deliver"];
			packages = new List<Package>(packageLogic.DeliverPackagesFromRegion(key));

			return View(packages);
		}
	}
}

opun.sks.Presentation.Website/Controllers/RegionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL.OutMemory;
using DALInterfaces.Exceptions;
using DALInterfaces.Interfaces.Agents;
using DALInterfaces.Interfaces.Presentation;
using DALInterfaces.Interfaces.Repositories;
using DALInterfaces.Interfaces.Services;
using EntityRepo.Entities;
using GeodataService;
using Microsoft.Practices.Unity;
using Microsoft.Practices.Unity.Configuration;
using Opitz_Unterbrunner_SKS;
using Opitz_Unterbrunner_SKS.PresentationLogic;
using log4net;

namespace opun.sks.Presentation.Website.Controllers
{
    public class RegionController : Controller
    {
	    private IRegionLogic regionLogic;
		IUnityContainer container { get; set; }
        private readonly log4net.ILog log;
	    public RegionController()
	    {
			container = new UnityContainer();
            log = log4net.LogManager.GetLogger(typeof(RegionController));
		    container.LoadConfiguration();

		    regionLogic = container.Resolve<IRegionLogic>();
	    }

        //
        // GET: /Region/
        public ActionResult Index()
        {
	        List<Region> regions = null;
	        try
	        {
                log.Info("Regions werden geladen");
		        regions = new List<Region>(regionLogic.GetAll());
	        }
	        catch (RepositoryException ex)
	        {
	
                log.Error("Website.RegionController.Index(), Fehler beim Übergeben der Regions an den View", ex);
		        regions = new List<Region>();
	        }
	        return View(regions);
        }

        //
        // GET: /Region/Edit/5
		public ActionResult Edit(int id)
		{
			Region region = null;
			try
			{
				region = regionLogic.GetById(id);
			}
			catch (RepositoryException ex)
			{
                log.Error("Website.RegionController.Edit(int id), Fehler beim Übergeben der Region an den View", ex);
			}

			return View(region);
		}

        //
        // POST: /Region/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
	            Region region = regionLogic.GetById(id);
	            region.Name = collection["name"];
	            region.Address.Location = collection["location"];
	            region.Address.Postcode = collection["postcode"];
				region.Address.Street = collection["street"];

				regionLogic.Update(region);

                return RedirectToAction("Index");
            }
            catch (RepositoryException ex)
            {
                log.Error("Website.RegionController.Edit(int id, FormCollection collection), Fehler beim Update der Region", ex);

                return View();
            }
        }

        //
        // GET: /Region/Delete/5
        public ActionResult Delete(int id)
        {
	        Region region = null;
	        try
	        {
		        region = regionLogic.GetById(id);
	        }
	        catch (RepositoryException ex)
	        {
                log.Error("Website.RegionController.Delete(int id), Fehler beim Laden der Region", ex);

		        region = null;
	        }

	        return View(region);
        }

        //
        // POST: /Region/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
        
	            Region delete = regionLogic.GetById(id);
				regionLogic.Delete(delete);

                return RedirectToAction("Index");
            }
            catch (RepositoryException ex)
            {
                log.Error("Website.RegionController.Delete(int id, FormCollection collection), Fehler beim Löschen der Region", ex);
                return View();
            }
        }
    }
}

opun.sks.Presentation.Website/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Linq;
using DAL.OutMemory;
using DALInterfaces.Interfaces.Agents;
using DALInterfaces.Interfaces.Presentation;
using DALInterfaces.Interfaces.Repositories;
using DALInterfaces.Interfaces.Services;
using EntityRepo.Entities;
using GeodataService;
using Microsoft.Practices.Unity;
using Microsoft.Practices.Unity.Configuration;
using Opitz_Unterbrunner_SKS;
using Opitz_Unterbrunner_SKS.PresentationLogic;
using log4net;

namespace opun.sks.Presentation.Website.Controllers
{
    public class UploadController : Controller
    {
	    private IRegionLogic regionLogic;
	    public IUnityContainer Container { get; set; }
        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

	    public UploadController()
	    {
		    Container = new UnityContainer();
			
		    Container.LoadConfiguration();

		    regionLogic = Container.Resolve<IRegionLogic>();
	    }

        //
        // GET: /Upload/
        public ActionResult Index()
        {
            return View();
        }

		//
		// GET: /Upload/Region/
	    public ActionResult Region()
	    {
		    return View();
	    }

		[HttpPost]
		// Post: /Upload/Region/
		public ActionResult Region(HttpPostedFileBase file)
		{
			if (file != null && ( file.ContentType.Equals("application/xml") || file.FileName.Contains(".xml") || file.ContentType.Equals("text/xml") ))
			{
                log.Info("Website.UploadController.Region(HttpPostedFileBase file), loading File");
				var reader = new StreamReader(file.InputStream);
				var doc = new XmlDocument();
				doc.Load(reader);
				
				if(regionLogic.ImportRegions(doc))
				return RedirectToAction("Index", "Region");
			}

			return View();
		}
	}
}

opun.sks.Presentation.Website/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>
	Package Management by
	<ul>
		<li>Stefan Opitz</li>
		<li>Andreas Unterbrunner</li>
	</ul>
</p>

opun.sks.Presentation.Website/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    <strong>Stefan Opitz:</strong>   <a href="mailto:if11b078@technikum-wien.at">stefan.opitz@technikum-wien.at</a><br />
    <strong>Andreas Unterbrunner:</strong> <a href="mailto:andreas.unterbrunner@technikum-wien.at">andreas.unterbrunner@technikum-wien.at</a>
</address>

opun.sks.Presentation.Website/Views/Home/Index.cshtml
@{
    ViewBag.Title = "SKS PackageManager";
}

<div class="jumbotron">
    <h1>Package Manager</h1>
    <p class="lead">Package Manager provides Services to manage and sort packages below you can find the functions we offer.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Region Management</h2>
        <p>
            View the available Regions, edit and delete them
        </p>
        <p><a class="btn btn-default" href="../Region/">Regions &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Region</h2>
        <p>Upload and XML file containing all the Regions or Packages you want to deliver to.</p>
        <p><a class="btn btn-default" href="../Upload/">Upload &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Package Management</h2>
        <p>View all non delivered Packages, filter them by Region and deliver Packages from a Region.</p>
        <p><a class="btn btn-default" href="../Package/">Packages &raquo;</a></p>
    </div>
</div>

opun.sks.Presentation.Website/Views/Package/Delivered.cshtml
@model IEnumerable<EntityRepo.Entities.Package>

@{
    ViewBag.Title = "Delivered";
}

<h2>Delivered</h2>

<p>
	The Packages from Region @Model.FirstOrDefault().Region.Key have been delivered successfully. @Html.ActionLink("Go Back", "Index")
</p>
<table class="table">
    <tr>
        <th>
            Recipient
        </th>
        <th>
            Delivered
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Recipient)
        </td>
        <td>
            @(item.Delivered ? "yes" : "no")
        </td>
    </tr>
}

</table>

opun.sks.Presentation.Website/Views/Package/Index.cshtml
@using System.Web.UI.WebControls
@model IEnumerable<EntityRepo.Entities.Package>

@{
    ViewBag.Title = "Package Overview";
}

<h2>Non-Delivered Packages</h2>

@if (!Model.Any())
{
	<p>
		All packages have been delivered.
	</p>
}
else
{

using (Html.BeginForm(null, "Package", "Index", FormMethod.Post, new {id = "formSelectRegion"}))
 {
	 @Html.AntiForgeryToken()
	 <p>
		 Select a Region to filter Packages 
		 @Html.DropDownList("selectRegion", new SelectList(ViewBag.RegionKeys, "Value", "Text"));
		 <input type="submit" value="Filter" class="btn btn-default" />
	 </p>
 }
using (Html.BeginForm(null, "Package", "Delivered", FormMethod.Post, new {id = "formDeliver"}))
 {
	 @Html.AntiForgeryToken()
	 <p>
		 <button type="submit" value="@ViewBag.Key" class="btn btn-block btn-primary col-md-3" name="deliver">Deliver Packages from Region @ViewBag.Key </button>
	 </p>
 }
	<table class="table">
		<tr>
			<th>
				Recipient
			</th>
			<th>
				Region Key
			</th>
			<th>
				Region Name
			</th>
		</tr>

		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Recipient)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Region.Key)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Region.Name)
				</td>

			</tr>
		}

	</table>
}

opun.sks.Presentation.Website/Views/Region/Delete.cshtml
@model EntityRepo.Entities.Region

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Region</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Key
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Key)
        </dd>

        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

opun.sks.Presentation.Website/Views/Region/Edit.cshtml
@model EntityRepo.Entities.Region

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@if (Model == null)
{
	<p>The Region you are trying to edit doesn't exist anymore</p>
}
else
{
 using (Html.BeginForm())
 {
	 @Html.AntiForgeryToken()

	 <div class="form-horizontal">
		 <h4>Edit Region @Model.Key</h4>
		 <hr />
		 @Html.ValidationSummary(true)
		 <!--input type="hidden" name="id" id="regionId" value="@Model.Id" /-->
		 <input type="hidden" name="key" id="regionKey" value="@Model.Key" />
		 @Html.HiddenFor(model => model.Id)

		 <div class="form-group">
			 <label for="name" class="control-label col-md-2">Name</label>
			 <div class="col-md-10">
				 <input id="name" type="text" class="form-control col-md-3" name="name" value="@Model.Name" />
			 </div>
		 </div>
		
		 <div class="form-group">
			 <label for="location" class="control-label col-md-2">Location</label>
			 <div class="col-md-10">
				 <input id="location" type="text" class="form-control col-md-3" name="location" value="@Model.Address.Location" />
			 </div>
		 </div>
		
		 <div class="form-group">
			 <label for="postcode" class="control-label col-md-2">Postcode</label>
			 <div class="col-md-10">
				 <input id="postcode" type="text" class="form-control col-md-3" name="postcode" value="@Model.Address.Postcode" />
			 </div>
		 </div>
		
		 <div class="form-group">
			 <label for="street" class="control-label col-md-2">Street</label>
			 <div class="col-md-10">
				 <input id="street" type="text" class="form-control col-md-3" name="street" value="@Model.Address.Street" />
			 </div>
		 </div>

		 <div class="form-group">
			 <div class="col-md-offset-2 col-md-10">
				 <input type="submit" value="Save" class="btn btn-default" />
			 </div>
		 </div>
	 </div>
 }
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

opun.sks.Presentation.Website/Views/Region/Index.cshtml
@model IEnumerable<EntityRepo.Entities.Region>

@{
    ViewBag.Title = "Region Overview";
}

<h2>Region Overview</h2>

@if (!Model.Any())
{
	<p>No Regions in System, Please @Html.ActionLink("upload Regions", "Region", "Upload") first </p>
}
else
{
	<table class="table">
		<tr>
			<th>
				Region Key
			</th>
			<th>
				Region Name
			</th>
			<th>
				Address Location
			</th>
			<th>
				Address Postcode
			</th>
			<th>
				Address Street
			</th>
			<th></th>
		</tr>

		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Key)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Address.Location)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Address.Postcode)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Address.Street)
				</td>
				<td>
					@Html.ActionLink("Edit", "Edit", new {id = item.Id}) |
					@Html.ActionLink("Delete", "Delete", new {id = item.Id})
				</td>
			</tr>
		}

	</table>
}

opun.sks.Presentation.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("OpUn Delivery System", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
	            <ul class="nav navbar-nav">
		            <li>@Html.ActionLink("Home", "Index", "Home")</li>
					<li>@Html.ActionLink("Regions", "Index", "Region")</li>
					<li>@Html.ActionLink("Packages", "Index", "Package")</li>
					<li>@Html.ActionLink("Upload", "Index", "Upload")</li>
		            <li>@Html.ActionLink("About", "About", "Home")</li>
		            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
	            </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Stefan Opitz & Andreas Unterbrunner</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

opun.sks.Presentation.Website/Views/Upload/Index.cshtml
@{
    ViewBag.Title = "Upload Introduction";
}

<h2>Upload</h2>

<div class="row">
	<div class="col-md-6">
		<h2>Region Upload</h2>
		<p>
			Upload a XML file containing all Regions.
		</p>
		<p>@Html.ActionLink("Upload Region", "Region", new { }, new { @class="btn btn-default" })</p>
	</div>
	<div class="col-md-6">
		<h2>Package Upload</h2>
		<p>Upload and XML file containing all Packages -- UNDER CONSTRUCTION.</p>
		<p><a class="btn btn-default" href="#" disabled>Package Upload</a></p>
	</div>
</div>

opun.sks.Presentation.Website/Views/Upload/Region.cshtml
@{
    ViewBag.Title = "Region Upload";
}

<h2>Upload a Region</h2>

<p>Upload a XML File containing all Regions.</p>

@using (Html.BeginForm("Region", "Upload", FormMethod.Post, new {EncType = "multipart/form-data"}))
{
	<label for="file">Filename:</label>
	<input type="file" name="file" id="file" class="form-control" />

	<input type="submit" class="btn btn-default" name="submit" value="Upload" />
}